import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import PageTransition from "@/components/shared/PageTransition";
import StairTransition from "@/components/shared/StairTransition";
import Footer from "@/components/shared/Footer";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	weidth: ["100", "200", "300", "400", "500", "600", "700", "800"],
	variable: "--font-jetbrainsMono",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${jetbrainsMono.variable} flex flex-col min-h-screen`}>
				<Header />
				<div className="flex-1 flex justify-center items-center">
					<StairTransition />
					<PageTransition>{children}</PageTransition>
				</div>
				<Footer />
			</body>
		</html>
	);
}
